### ISSUE TITLE
[v5] schema import doesn't work correctly when schemas is at the same level as the endpoints file

### ISSUE THREAD

**Issue by eddiecooro** [orval-labs/orval#120]
## What are the steps to reproduce this issue?
1. build a project with the following config:
```js
module.exports = {
  petstore: {
    output: {
      mode: 'split',
      target: './api/petstore/index.ts',
      schemas: './api/petstore/models',
	  client: 'react-query'
    },
    input: {
      target: './petstore.yaml',
    },
  }
}
```

## What happens?
in the `api/petstore/index.ts` the models are getting imported from `models`
![image](https://user-images.githubusercontent.com/20463083/117786727-117b6680-b25b-11eb-8c24-3af541646481.png)

## What were you expecting to happen?
The import path should be `./models`
![image](https://user-images.githubusercontent.com/20463083/117786834-28ba5400-b25b-11eb-98e8-2a75c9204793.png)

## What versions are you using?
**Package Version:** 5.1.2

**Comment by Eddie-CooRo** [comment]
I'm working on a fix

**Comment by anymaniax** [comment]
Thanks for your help
