### ISSUE TITLE
Add support for CSV/explode=false query parameters "styles"

### ISSUE THREAD

**Issue by ashb** [orval-labs/orval#1285]
There is a feature of OpenAPI 3 that lets you change the style of how repeated parameters are specified https://spec.openapis.org/oas/v3.0.3#parameterStyle and https://spec.openapis.org/oas/v3.0.3#style-examples

The particular use case I have is to set `explode=false` to have CSV parameters rather than multiple query params.

Minimal spec file:

```json
{
  "info": {
    "title": "My API",
    "version": "1.0.0"
  },
  "openapi": "3.0.3",
  "paths": {
    "/test/": {
      "get": {
        "parameters": [
          {
            "in": "query",
            "explode": false,
            "name": "parameter",
            "required": true,
            "schema": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
```

When called with multiple params this should result in `?parameter=a,b,c` but it always/only produces  `?parameter=a&parameter=b&parameter=c`. 

Tested with version 6.25.0

**Comment by programm-ingovals** [comment]
Note there also how arrays should be handled according to OpenApi spec

`color=blue&color=black&color=brown`

But **Orval** will do 

`color[]=blue&color[]=black&color[]=brown`

Which I've never seen mentioned in the OpenApi spec.
Which I guess is fine if we could just turn it off.

**Comment by austin-agronick** [comment]
@programm-ingovals that is an [axios feature](https://stackoverflow.com/a/76517213) that can be configured by adding the request key to the options parameter or the output override object:
```
request: {
    paramsSerializer: {
      indexes: null
    }
  }
```

**Comment by programm-ingovals** [comment]
> @programm-ingovals that is an [axios feature](https://stackoverflow.com/a/76517213) that can be configured by adding the request key to the options parameter or the output override object:
> 
> ```
> request: {
>     paramsSerializer: {
>       indexes: null
>     }
>   }
> ```

Thanks, will check that out.

**Comment by soartec-lab** [comment]
i think fix by #1580 so related.

**Comment by soartec-lab** [comment]
I close this issue.
When you use `axios` as a client, use `paramsSerializer`. and when you use `fetch` as a client, it can be controlled by the `explode` property in `OpenAPI`.

**Comment by melloware** [comment]
For others reading this I ran into this with Axios and was confused by the fix i thought it was an Orval config but its an Axios config on Axios Configuration you need to set.  I use Axios Request Interceptors so my fix went there. Example...

```js
/ Add request interceptor for auth tokens
axiosInstance.interceptors.request.use(
  (config) => {
    // Get authentication data from session storage
    const userDataString = sessionStorage.getItem(`oidc.user:${import.meta.env.VITE_OIDC_AUTHORITY || 'http://localhost:8020/realms/keycloak'}:keycloak-api`);

    if (userDataString) {
      try {
        const userData = JSON.parse(userDataString);
        if (userData.access_token) {
          config.headers.Authorization = `Bearer ${userData.access_token}`;
        }
      } catch (error) {
        console.error('Error parsing authentication data from session storage:', error);
      }
    }

    // serialize string[] as comma separated strings
    config.paramsSerializer = {
      indexes: null, // array indexes format (null - no brackets, false - empty brackets, true - brackets with indexes)
    };

    return config;
  },
  (error) => Promise.reject(error)
);
```
