### ISSUE TITLE
A better way to manage dynamic API url for Angular HTTP Client

### ISSUE THREAD

**Issue by spawnrider** [orval-labs/orval#1460]
## What are the steps to reproduce this issue?

I need to override the baseURL api at runtime depending on the environment configuration.
For exemple : 
`GET '<baseURI>/api/myendpoint'`

## What happens?
At the moment, the only way to do this is to use a custom HTTP interceptor (https://orval.dev/guides/set-base-url#angular-http-client). This is not a practical solution, as this interceptor will be triggered for ALL my app requests (Orval-generated API or not)

## What were you expecting to happen?
A convenient way to override the API URL at the runtime based on another (configuration) service without using a global HTTP interceptor.
There is multiple possibilites : 
1. Override the baseURI using the constructor or a specific setter (i.e. setBaseURI)
2. Use a custom function / class to override the baseURI

May you have another / better idea on the subject ?  

## What versions are you using?

**Operating System:** Windows 11
**Package Version:** 6.26
**Browser Version:**  N/A

**Comment by soartec-lab** [comment]
@spawnrider 
you can use custom client instead of interceptor. if you need detail, please see the sample app bellow.

https://github.com/orval-labs/orval/blob/master/samples/angular-app/src/api/endpoints/pets/pets.service.ts#L46-L49

**Comment by soartec-lab** [comment]
I'll update guide later.
