### ISSUE TITLE
mock does not generate correct bigint type

### ISSUE THREAD

**Issue by thegenius** [orval-labs/orval#1472]
when field type is bigint, mock will use faker.number.int() to generate number value, which cause error.

**Comment by thegenius** [comment]
and it will be better to generate mock in a separated file

**Comment by melloware** [comment]
PR is welcome i would think this would be easy fix for bigint

**Comment by thegenius** [comment]
As I have read the source code of the mock package, it's not so hard to fix this.
But it's a big problem to create a correct PR, but there is no tests with mock,
I can't find any test code for mock, so if it be possible to create a basic tests suite.
And after we get test suite, then we can create correct PR to help this project.

**Comment by soartec-lab** [comment]
Hi @thegenius, Thanks for making a good issue.

We have tests in the `tests` directory.
In this case, I think you can add a test by adding the `fomat: int64` property to the [`tests/specifications/format](https://github.com/orval-labs/orval/blob/master/tests/specifications/format.yaml).yaml` schema. Would you work on this?
