### ISSUE TITLE
What does mode do?

### ISSUE THREAD

**Issue by agamm** [orval-labs/orval#1479]
## What are the steps to reproduce this issue?

No explanation at https://orval.dev/reference/configuration/output#mode

## What happens?

…

## What were you expecting to happen?
Have some sentences explaining the different modes.

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?

**Operating System:** …
**Package Version:** …
**Browser Version:** …

**Comment by melloware** [comment]
Marked it as a good first issue!

**Comment by soartec-lab** [comment]
@agamm 

that's already exist explains, so if you wanna know different to try generate each mode. And we always welcome update guide from you 🙌
