### ISSUE TITLE
Model filename casing

### ISSUE THREAD

**Issue by agamm** [orval-labs/orval#1499]
## What are the steps to reproduce this issue?

1. Generate a schema with models

## What happens?

Model file names' first lettter is lowercase for some reason
![image](https://github.com/anymaniax/orval/assets/1269911/a627a8fe-f66c-4864-8fed-ce7973d6c5b7)

## What were you expecting to happen?

Be in TitleCase.

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?

**Operating System:** Ubuntu
**Package Version:** 6.30.2

**Comment by melloware** [comment]
Do you have a reproducer?  Is it like that because that is how it is in your openAPI Spec?

**Comment by agamm** [comment]
Just a standard FastAPI openapi.json?

**Comment by melloware** [comment]
yeah i was seeing if something is "helloWorld" in the JSON does it come out as that variable name in the generated code?

**Comment by agamm** [comment]
The openai.json looks fine capital-wise:
![image](https://github.com/anymaniax/orval/assets/1269911/e7bef1f2-5bcf-4244-8806-6a9f117d4a6e)

**Comment by melloware** [comment]
got it.

**Comment by soartec-lab** [comment]
Same as #428
