### ISSUE TITLE
Vue Query: error ref contains a ref to a Promise

### ISSUE THREAD

**Issue by pbrzosko** [orval-labs/orval#1534]
## What are the steps to reproduce this issue?

1. Generate code with client = vue-query and httpClient = fetch
2. Inspect generated types for one of the APIs

## What happens?

Error ref contains a ref to a promise: 
![image](https://github.com/user-attachments/assets/d51640ca-614b-4f32-bf16-aa4376d27354)

## What were you expecting to happen?

According to vue-query docs, it should be: `error: null | TError`

## What versions are you using?

**Operating System:** OSX Sonoma 14.5
**Package Version:** 7.0.0
**Browser Version:** 126.0.6478.183 (Official Build) (arm64)

**Comment by soartec-lab** [comment]
@pbrzosko 
Thanks for made this report.
Could you tell me minimum reproduce openapi and full generated function ?

**Comment by pbrzosko** [comment]
Yes, there it is: https://github.com/pbrzosko/orval-vue-query-issue

- npm install
- npm run orval

Please go to TestComponent and inspect type of the error ref.

![image](https://github.com/user-attachments/assets/51adea6e-715b-46a3-b8df-ebac2e0316a3)

**Comment by davidysoards** [comment]
i see same issue using
spec: https://github.com/dys-org/mono/blob/orval-fetch-query-bugs/go/oapi-todo/api/openapi.yaml
generated: https://github.com/dys-org/mono/blob/orval-fetch-query-bugs/js/packages/oapi-todo/src/api.ts
<img width="620" alt="Screenshot 2024-07-28 at 12 59 06 AM" src="https://github.com/user-attachments/assets/542eaa37-404b-4e14-b27b-4326355a038a">

**Comment by soartec-lab** [comment]
@pbrzosko @davidysoards 
overrides `TError` to use `Promise<unknown>` as `fetch` response to error presented by `openapi`, what kind of scene do you want to use the case for?

**Comment by pbrzosko** [comment]
I don't get the question. What do you mean?

**Comment by soartec-lab** [comment]
First, I think that wrapping the response in a `Ref` is the expected behavior.

https://tanstack.com/query/v4/docs/framework/vue/typescript#type-inference

And if the success response is obvious, I would like to inject the defined success response and return type.
So I don't know the details of the pain. Could you please tell me more details?

**Comment by soartec-lab** [comment]
And this problem isn't just about fetch. This problem also occurs when using `axios`.

**Comment by pbrzosko** [comment]
The pain is that error is a Ref to a promise that returns the error, not the error itself. And to get the error I need to await it.

**Comment by soartec-lab** [comment]
@pbrzosko 
in another word, you want `Ref<Pet> | Ref<null>` instead of `Ref<Promise<Pet> | Ref<null>` right ?
And `fetch` response is `Promise` so i think that can't remove `Promise`. What do you think?

**Comment by pbrzosko** [comment]
Oh man, yes, but I am talking about error ref. So instead of `Ref<Promise<Error>> | Ref<null>` I want to have `Ref<Error> | Ref<null>` or even better `Ref<Error | null>`.
Yes, I get fetch response is Promise, but error ref is set to null when fetch is being executed, and then to an error if fetch ended with it. So why do I need to await the error?

Also have a look at the vue-query docs. They return a ref with error, not ref with a promise to get the error:
https://tanstack.com/query/latest/docs/framework/react/reference/useQuery

![image](https://github.com/user-attachments/assets/ca1ebe94-d2aa-45fd-ba4b-c53c8937df9c)

**Comment by soartec-lab** [comment]
Okay, I ganna remove unnecessary `Promise` from error response type when using query clients
