### ISSUE TITLE
OpenAPI validation appears to not be working

### ISSUE THREAD

**Issue by rschelling** [orval-labs/orval#1537]
## What are the steps to reproduce this issue?

1. Enable `validation: true` in the input configuration.
2. Use Orval to generate typescript from an OpenAPI JSON file

## What happens?

I had an error in my OpenAPI specification and Orval did generate invalid type declaration (The property name was there, but the actual type was missing).
Even after enabling validation, Orval still generated the invalid typescript code.

The part in the OpenAPI File looked like this:
```json
"whiteBalanceSettingsLeft": {
  "oneOf": [],
  "discriminator": {
    "propertyName": "type",
    "mapping": {}
  }
},
```

And the generated type was:
```ts
whiteBalanceSettingsLeft: ;
```
Afterwards i used the IBM OpenAPI Validator without any custom configuration and it detected that error and also a lot of others regarding the wrong casing for parameter names, etc.

## What were you expecting to happen?

I expected Orval to through an error and not generate invalid typescript code.

## Any other comments?

I would appreciate it, if you could tell me, if this is the expected behaviour and if i should validate the OpenAPI file before using Orval. Thanks!

## What versions are you using?

**Operating System:** Ubuntu
**Package Version:** 6.31.0
**Browser Version:** …

**Comment by melloware** [comment]
I would have expected this to validate so this is a bug.

**Comment by melloware** [comment]
@rschelling the code is right here if you want to debug and help us fix it?

https://github.com/orval-labs/orval/blob/master/packages/core/src/utils/validator.ts

**Comment by rschelling** [comment]
@melloware I will take a look at it and see what i can do, but no promises :-)
