### ISSUE TITLE
New Client: xior

### ISSUE THREAD

**Issue by mattiaseyram** [orval-labs/orval#1538]
# Description

https://github.com/suhaotian/xior is a good alternative to axios, could this be added easily? (or simply swapping out axios with xior in a custom handler)

**Comment by melloware** [comment]
I would probably have to be coded. We just added a new `fetch` client for people who don't want to use Axios.

**Comment by soartec-lab** [comment]
Thank you for your suggestion. However, there are no plan to support that new client at this point. so i close this.
