### ISSUE TITLE
[Regression in 7.0.1] Generated MSW mock handlers have type check error

### ISSUE THREAD

**Issue by severinh** [orval-labs/orval#1566]
## What are the steps to reproduce this issue?

1. Upgrade from 6.31.0 to 7.0.1
2. For routes without response body, the generated MSW mock handler does not type-check. The resolver passed to `http.post` has the signature `(info) => { ... }`, but it should be async `(info) => {`, because the generated body contains an `await`.

## What happens?

Here's a screenshot illustrating the problem. It's the diff in our generated code before and after upgrading to 7.0.1.

The problem only seems to affect routes without a response body. It seems that before 7.0.1, it was not possible to override the handler for such a route. With 7.0.1, the generated code now seems to be more similar to routes with a response body.

![Screenshot 2024-08-07 at 10 22 43](https://github.com/user-attachments/assets/60e02612-61b8-41ce-8e7b-7d8d35911e7f)

Currently, this blocks us from upgrading to orval 7.0.1, because the generated MSW code does not compile.

## What were you expecting to happen?

Either:
1. Add the missing `async` before `(info) => {`, which would be consistent with other generated mock handlers.
2. Revert the behavior to how it was in 6.31.1.

## Any logs, error output, etc?

N/A

## Any other comments?

Thanks for all your work on orval! It's a pleasure to work with orval.

## What versions are you using?

7.0.1

**Comment by melloware** [comment]
PR is welcome you should be able to find the regression in the code between 6.31 and 7.0.1

**Comment by melloware** [comment]
Is this PR for the issue?  https://github.com/orval-labs/orval/pull/1567 ?

**Comment by severinh** [comment]
Amazing! Thanks for fixing this issue so quickly, @karlismelderis-mckinsey.
