### ISSUE TITLE
react-query: check for NULL skipped inside "anyOf" list of types

### ISSUE THREAD

**Issue by jsmchu** [orval-labs/orval#1569]
## What are the steps to reproduce this issue?

1. 
In input json file add a schema that contains list of types listed inside "anyOf", including **null** type:

            "Something": {
                "properties": {
                    "some_var": {
                        "anyOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "title": "Some var"
                    }
                },
                "type": "object",
                "title": "Something"
            },
2. Generate a clients for **client: "react-query",**
3. Generated code:

		export type SomethingSomeVar = string | null;

		export interface Something {
		  some_var?: SomethingSomeVar ;
		  }
		export const operation = (
		  Something: Something,
		  options?: AxiosRequestConfig
		): Promise<AxiosResponse<unknown>> => {
		  const formUrlEncoded = new URLSearchParams();
		  if (Something.some_var !== undefined) {
		    formUrlEncoded.append('some_var', something.some_var);
		  }
		  }
	  

## What happens?
There is created if condition that is checking if "Something.some_var" is not equal to undefined, but we are missing also a NULL check. 

## What were you expecting to happen?
We should get a:
  if (Something.some_var !== undefined &&  Something.some_var !== null) 
  or at least
    if (Something.some_var) 

…

## Any logs, error output, etc?

…

## Any other comments?
…

## What versions are you using?
	  System:
	    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
	    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
	    Memory: 9.35 GB / 15.33 GB
	    Container: Yes
	    Shell: 5.1.16 - /bin/bash
	  npmPackages:
	    axios: ^1.6.1 => 1.6.8
	    orval: ^7.0.1 => 7.0.1
Please execute `npx envinfo --system --npmPackages orval,zod,axios,msw,@tanstack/react-query` and paste the results here.

**Comment by soartec-lab** [comment]
I think this issue resolved by #1646, so I'll close it.

**Comment by soartec-lab** [comment]
Hi, @jsmchu 

I think this will be fixed in the next release, so give it a try when it's released 👍
