### ISSUE TITLE
Schema allOf generation does not follow Swagger spec

### ISSUE THREAD

**Issue by MibbitTom** [orval-labs/orval#1570]
## What are the steps to reproduce this issue?

I want to use Orval to generate an API that uses inheritance. But, my subclass' fields are being generated as optional even though I have marked them as required.

1. Use Orval to generate models using the following Yaml:
```
openapi: 3.0.1
info:
  contact:
    email: xxx
    name: xxx
    url: xxx
  description: xxx
  title: xxx
  version: '0.1'
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/notifications/mine:
    get:
      operationId: getMyNotifications
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/NewTicketNotification'
          description: OK
      summary: Get my notifications
      tags:
        - Notifications
components:
  schemas:
    NewTicketNotification:
      required:
        - ctime
        - id
        - ticketId
        - type
        - userId
      type: object
      allOf:
        - $ref: '#/components/schemas/Notification'
        - type: object
          properties:
            ticketId:
              type: integer
              format: int32
            userId:
              type: integer
              format: int32
    Notification:
      required:
        - ctime
        - id
        - type
      type: object
      properties:
        ctime:
          type: string
          format: date-time
        id:
          type: integer
          format: int32
        type:
          type: string
      discriminator:
        propertyName: type
```

## What happens?

Orval generates the following:

```
export interface Notification {
  ctime: string;
  id: number;
  type: string;
}

export type NewTicketNotificationAllOf = {
  ticketId?: number;
  userId?: number;
};

export type NewTicketNotification = Notification & NewTicketNotificationAllOf;
```

## What were you expecting to happen?

The fields in the subclass `NewTicketNotificationAllOf` should be required. E.g.
```
export type NewTicketNotificationAllOf = {
  ticketId: number;
  userId: number;
};
```

They actually are generated as required if I manually add `required` in the properties of the allOf. E.g.
```
NewTicketNotification:
      required:
        - ctime
        - id
        - ticketId
        - type
        - userId
      type: object
      allOf:
        - $ref: '#/components/schemas/Notification'
        - type: object
          required:
          - ticketId
          - userId
          properties:
            ticketId:
              type: integer
              format: int32
            userId:
              type: integer
              format: int32
```

But I shouldn't have to do that! `NewTicketNotification` already has `ticketId` declared as required. This should supersede the non-required property included in the allOf.

## Any other comments?
Swagger's editor and codegen tool interpret the YAML correctly so I think I have interpreted the spec correctly! (See pictures)

I presume the parser needs a change to use the oneOf/allOf/anyOf key to make properties required (if needed) or leave them alone if they are already required.

![image](https://github.com/user-attachments/assets/b02d0195-3a63-4290-90ba-faaf19414b8f)
![image](https://github.com/user-attachments/assets/1069ec15-2f0f-46f6-8c55-03ff4104868c)

## What versions are you using?
Latest code built from Github.

System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor
    Memory: 2.69 GB / 15.55 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash

**Comment by melloware** [comment]
I think this is similar to https://github.com/orval-labs/orval/pull/861

**Comment by MibbitTom** [comment]
Sweet! Yes, that looks to be referring to the same issue.

Do you know if the maintainers are looking into that still? Pull request looks pretty dead...

**Comment by melloware** [comment]
That PR is way out of date. Probably need a new Pr if you are interested .

**Comment by Samuel-Morgan-Tyghe** [comment]
Ditto on this as-well^^

**Comment by melloware** [comment]
@MGabr has kindly submitted a PR

**Comment by MGabr** [comment]
Is there a planned time for the next version? :) I would benefit a lot from the fix and it seems the two remaining PRs for the the milestone are stalled

**Comment by melloware** [comment]
I just pinged @anymaniax about a release
