### ISSUE TITLE
Zod: generation of typed tuples produces illegal zod array syntax

### ISSUE THREAD

**Issue by helt** [orval-labs/orval#1592]
## What are the steps to reproduce this issue?

1. check out referenced PR
2. in tests: generate and build

## What happens?

zod generator produces `zod.array()`, which is illegal syntax since `error TS2554: Expected 1-2 arguments, but got 0.`

## What were you expecting to happen?

Produce a typed tuple, similar to:

```zod.tuple(zod.string(), zod.object())```

## Any logs, error output, etc?

```
generated/zod/example-v3-1.ts:25:24 - error TS2554: Expected 1-2 arguments, but got 0.

25   "example_tuple": zod.array().min(postApiSampleResponseExampleTupleMin).max(postApiSampleResponseExampleTupleMax).optional(),
                          ~~~~~~~

  node_modules/zod/lib/types.d.ts:1055:49
    1055 declare const arrayType: <T extends ZodTypeAny>(schema: T, params?: RawCreateParams) => ZodArray<T, "many">;
                                                         ~~~~~~~~~
    An argument for 'schema' was not provided.
```

## Any other comments?

more issues pop up which are not *my* main concern, currently.

## What versions are you using?

```
npx envinfo --system --npmPackages orval,zod,axios,msw,swr,@tanstack/react-query,@tanstack/vue-query,react,vue
Need to install the following packages:
envinfo@7.13.0
Ok to proceed? (y) y

  System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 13.61 GB / 31.31 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  npmPackages:
    @tanstack/react-query: ^4.22.0 => 4.22.0 
    @tanstack/vue-query: ^4.22.0 => 4.22.0 
    axios: ^0.26.1 => 0.26.1 
    msw: ^2.0.2 => 2.0.2 
    react: ^18.3.1 => 18.3.1 
    swr: ^2.2.4 => 2.2.4 
    vue: ^3.3.4 => 3.3.4 
    zod: ^3.23.8 => 3.23.8 
```

**Comment by helt** [comment]
reuses test cases of prefixItems added in https://github.com/orval-labs/orval/issues/890

**Comment by helt** [comment]
A similar issue was reported in kubb, but since kubb is deprecated, i was recommended to switch to orval. https://github.com/kubb-labs/kubb/issues/1018

**Comment by helt** [comment]
https://github.com/kubb-labs/kubb/commit/35b7a0a7822716b9625c0c96a904ec0c7b9ebe4a

**Comment by helt** [comment]
Hey. I looked into the issue. 
So far, it is half-way working. An issue I have currently is that `min` and `max` are added to my `tuple` call. However, zod does not allow it to follow `tuple()` calls. Any ideas how to get rid of it?. 

More questions:
* is `orval$ yarn run build && cd tests && yarn run generate && cd ..` really the quickest way to rerun the tests after changing the logic in `pacakges/zod/index.ts`?
* What is `consts` for? Are there edge cases I have to know about?

Given a 
```
const arrayWithPrefixItemsSchema: SchemaObject31 = {
  type: "array",
  prefixItems: [
    {type: "string"},
    {}
  ],
  items:
    {type: "number"},
}
```

According to [openapi v3.1 spec](https://json-schema.org/draft/2020-12/json-schema-core#name-prefixitems), the goal of parsing `prefixItems`  is to generate something like: 
```
z.tuple([z.string(), z.object()]).rest(z.number())
``` 


Currently I am doing the following:
* in `generateZodValidationSchemaDefinition`, the `array` case has to be altered to adhere prefixItems constraints. If `prefixItems` exists, 
    * [x] a `tuple` has to be pushed into functions instead of `array`, 
    * [x] each prefixItem has to be parsed and nested into the tuple
    * [x] if `items` exists, a `rest` function has to be pushed after the `tuple` with the schema in items
* in `parseZodValidationSchemaDefinition`:
  * [x] logic to add positional parameters to `tuple`
  * [x] logic for the `rest` functions has to be added
* [ ] prevent `.min().max()` on tuple.

**Comment by melloware** [comment]
Awesome job @helt  if you don't mind reviewing there are a few more open Zod issues that would be a huge help if you wanted to tackle them;  https://github.com/orval-labs/orval/issues?q=is%3Aissue+is%3Aopen+label%3Azod
