### ISSUE TITLE
Feature Request: Ability to exit on validation warnings

### ISSUE THREAD

**Issue by ezequiel** [orval-labs/orval#1603]
## Description

Right now we only exit when there are validation errors. We also want the ability to exit on warnings, since we don't want to introduce warnings into the codebase.

Warnings also generally point out good things we should fix anyway, e.g.

```
=> S2OError: (Patchable) path parameters must be required:true [limit in get:/api/v1/my_endpoint]
```

**Comment by ezequiel** [comment]
Hmm, for some reason `process.exit(1)`s are stripped in the @orval/core bundle:

```ts
// src/utils/validator.ts
var ibmOpenapiRuleset = require("@ibm-cloud/openapi-ruleset");
var { Spectral } = require_dist10();
var ibmOpenapiValidator = async (specs) => {
  const spectral = new Spectral();
  spectral.setRuleset(ibmOpenapiRuleset);
  const { errors, warnings } = await spectral.run(specs);
  if (warnings && warnings.length) {
    ibmOpenapiValidatorWarnings(warnings);
  }
  if (errors && errors.length) {
    ibmOpenapiValidatorErrors(errors);
  }
};
```

**Comment by melloware** [comment]
I think it was reported here too about the Exit Code: https://github.com/orval-labs/orval/issues/1497

Something funky is going on.

**Comment by yoshi2no** [comment]
> Hmm, for some reason process.exit(1)s are stripped in the @orval/core bundle (at least the one published to NPM, not a local build):

@ezequiel 

I think it’s likely because the commit that added `process.exit(1)` was part of the latest [7.1.0 release](https://github.com/orval-labs/orval/releases/tag/v7.1.0). From the code you shared, it seems like you might be using a bundle of @orval/core from before that 7.1.0 release 👀

**Comment by melloware** [comment]
ok @ezequiel can you try 7.1.0 now that is is out?
