### ISSUE TITLE
Add option for @ts-nocheck  for all files in config

### ISSUE THREAD

**Issue by master8848** [orval-labs/orval#1615]
## What happens?

I am getting some errors due to how my api docs are setup but code would work but typechecking is not letting me push changes

Running typecheck is giving issue and cannot exclude that folder in tsconfig 

## Any other comments?

Give option to add "@ts-nocheck" in config file 

## What versions are you using?

  System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 319.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    @tanstack/react-query: ^5.51.23 => 5.51.23 
    orval: ^7.0.1 => 7.0.1 
    react: ^18.3.1 => 18.3.1 
    zod: ^3.23.8 => 3.23.8

**Comment by melloware** [comment]
I think you might be able to do this with headers option.

```yml
petstore: {
    output: {
      override: {
        header: (info: InfoObject): String[] => [
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
      },
    },
```

That is how you can override the header generation you should be able to add `@ts-nocheck`

**Comment by slikts** [comment]
The header is wrapped in `/** */`, so adding `// @ts-nocheck` there doesn't work.

**Comment by melloware** [comment]
@slikts do it like this...

```js
header: (info: InfoObject): String[] => { return "// @ts-nocheck\r\n" },
```

**Comment by tokuhirom** [comment]
fyi: i used perl post process for this issue.

```bash
perl -i -pe 'print "// \@ts-nocheck\n" if $. == 1' src/api.ts
```
