### ISSUE TITLE
FETCH: Custom headers provided in options are overwritten for POST

### ISSUE THREAD

**Issue by sharenz** [orval-labs/orval#1622]
## What are the steps to reproduce this issue?

1. Use the FETCH Client
2. Set a custom header using options
3. Make a POST call

## What happens?

The custom header gets overwritten

## What were you expecting to happen?

The custom headers are merged with the other headers.

## Proposed fix by shodai on discord:

```ts
Indeed, this may needs to be merge options.headers and { 'Content-Type': 'application/json' } like a follow:

return customFetch<Promise<createPetsResponse>>(getCreatePetsUrl(), {
  ...options,
  method: 'POST',
  headers: { 'Content-Type': 'application/json', ...options.headers },
  body: JSON.stringify(createPetsBodyItem),
});
```

**Comment by soartec-lab** [comment]
Thanks for made it 👍

**Comment by Poylar** [comment]
> Thanks for made it 👍

Is there any temporary solution. This problem is exhausting me.
And is it possible to get information about when this can be fixed?
week. month, day?
The thing is that I have an urgent project and I need to understand whether to continue working with orval or take something else for generation.

**Comment by vtmnts666** [comment]
+
Same problem here

**Comment by soartec-lab** [comment]
@Poylar 

It will probably take a week or a month to fix it.
And you can avoid this problem by using custom fetch as a workaround.

https://orval.dev/guides/fetch-client#custom-fetch-client
https://github.com/orval-labs/orval/blob/master/samples/next-app-with-fetch/custom-fetch.ts#L32-L45

**Comment by soartec-lab** [comment]
I fixed it  by #1627 👍

**Comment by Poylar** [comment]
> @Poylar
> 
> It will probably take a week or a month to fix it. And you can avoid this problem by using custom fetch as a workaround.
> 
> https://orval.dev/guides/fetch-client#custom-fetch-client https://github.com/orval-labs/orval/blob/master/samples/next-app-with-fetch/custom-fetch.ts#L32-L45

yeah, im already using custom fetch, but i cant override header outside function. for example

```
export const updateCart = async (
  updateCartBody: UpdateCartBody,
  options?: RequestInit
): Promise<updateCartResponse> => {
  const res = await fetch(getUpdateCartUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(updateCartBody)
  });
  const data = await res.json();

  return { status: res.status, data };
};
```

i cant override with
```

await updateCart(body,{
headers: {
...
}
})

**Comment by soartec-lab** [comment]
@Poylar 
yes. Currently it can't be overridden with `optional` when calling arguments.
So I ask when the next release is planned.

**Comment by soartec-lab** [comment]
@Poylar @sharenz @scottdickerson

A new version V 7.1.1 with the fix has been released, please check it here 👍
