### ISSUE TITLE
Is there a migration guide to v7?

### ISSUE THREAD

**Issue by KaitakuShiba** [orval-labs/orval#1641]
Thank you for creating a great product.

## What are the steps to reproduce this issue?

migrating orval v6 to v7

## What happens?
Is there a migration document somewhere to get orval from v6 to v7?
In my development environment, when I generate from the same openapi.yaml, I get a build error because the generated file contains variables that cannot be referenced in v7.

## What were you expecting to happen?
generated/example.ts

- v6
```ts
foo: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(BarCode)),
      ]),
```

- v7
```ts
foo: faker.helpers.arrayElement([
        faker.helpers.arrayElement(Object.values(bar.Code)), <= bar is not found
      ]),
```

**Comment by melloware** [comment]
Hmm no migration guide that looks like a bug. I think it was just fixed: https://github.com/orval-labs/orval/issues/1620

It will be in next release.
