### ISSUE TITLE
add headers to response

### ISSUE THREAD

**Issue by nimo23** [orval-labs/orval#1694]
## What are the steps to reproduce this issue?

1. Generate queries by using fetch api
2. Look into the response object
3. No headers are in the response object

## What happens?

No headers will be in the response object. The code looks like:

```
  const res = await fetch(getTaskResourceListAllUrl(params),
  {      
    ...options,
    method: 'GET'
  }

  )
  const data = await res.json()
  // Issue: please add the "res.headers" into the return statement
  return { status: res.status, data }
}
```

## What were you expecting to happen?

Add `headers` in the `response` object, at least when `openapi.json` describes custom headers for an API endpoint.

## What versions are you using?
"orval": "^7.2.0",

**Comment by melloware** [comment]
@nimo23 can you review my PR i think that is what you are asking for?
