### ISSUE TITLE
How to modify generated types for custom fetch client?

### ISSUE THREAD

**Issue by SamyZog** [orval-labs/orval#1707]
## What are the steps to reproduce this issue?

Types are generated in a certain structure when using the fetch client instead of axios

{ data, status }, is there a way to return it as only data

example
```
export type userRigsListResponse = {
  data: PaginatedRigListUserListDTO;
  status: number;
};
```

1. …
2. …
3. …

## What happens?

…

## What were you expecting to happen?

…

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?

Please execute `npx envinfo --system --npmPackages orval,zod,axios,msw,swr,@tanstack/react-query,@tanstack/vue-query,react,vue` and paste the results here.

**Comment by melloware** [comment]
Yes see this answer for 7.2.0: https://gurubase.io/g/orval/orval-fetch-client-return-only-data

On 7.3.0 its `includeHttpResponseReturnType`

**Comment by SamyZog** [comment]
Thank you!
