### ISSUE TITLE
svelte-query example app works only intermittantly

### ISSUE THREAD

**Issue by JPVan** [orval-labs/orval#172]
## What are the steps to reproduce this issue?
1. Go to samples/svelte-query
2. `yarn`
3. `yarn dev`

## What happens?

local dev server launches at port 3000. Sometimes it doesn't list any names, and sometimes a page refresh will list some names. 

## What were you expecting to happen?
I was expecting the svelte-query example app to work consistently.

## Any logs, error output, etc?

**Sometimes a page refresh give a list of names under the Orval logo. Sometimes it gives this error in the browser console: 
[vite] connecting...**

client:202 [vite] connected.
index.js:648 [MSW] Mocking enabled.
rest-deps.js:84 [MSW] 11:23:58 GET /v1/pets (200)
index.mjs?v=797ae7f0:1650 Uncaught (in promise) Error: {#each} only iterates over array-like objects.
    at validate_each_argument (index.mjs:1650)
    at create_else_block (pets.svelte:41)
    at Object.update [as p] (pets.svelte:316)
    at update (index.mjs:764)
    at flush (index.mjs:732)

**Sometimes a page refresh works with the following browser console output:** 

[vite] connecting...
client:202 [vite] connected.
xhr.js:177 GET http://localhost:3000/v1/pets 404 (Not Found)
index.js:648 [MSW] Mocking enabled.
rest-deps.js:84 [MSW] 11:26:28 GET /v1/pets (200)

**Small detail, but also Vite fails to load source maps at build:** 

11:23:12 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/query/Query.svelte.
11:23:12 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/infiniteQuery/InfiniteQuery.svelte.
11:23:12 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/queries/Queries.svelte.
11:23:12 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/queryClientProvider/QueryClientProvider.svelte.
11:23:12 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/isMutating/IsMutating.svelte.
11:23:12 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/mutation/Mutation.svelte.
11:23:12 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/isFetching/IsFetching.svelte.
11:23:12 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/hydration/Hydrate.svelte.
11:23:14 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/queryClientProvider/QueryClientProvider.svelte.
11:23:14 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/query/Query.svelte.
11:23:14 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/infiniteQuery/InfiniteQuery.svelte.
11:23:14 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/queries/Queries.svelte.
11:23:14 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/isMutating/IsMutating.svelte.
11:23:14 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/mutation/Mutation.svelte.
11:23:14 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/isFetching/IsFetching.svelte.
11:23:14 AM [vite] Failed to load source map for /node_modules/@sveltestack/svelte-query/svelte/hydration/Hydrate.svelte.

## Any other comments?

Thank you for making Orval, it looks really awesome! I was excited to use it in a production project, but the example apps not working is giving some of my coworkers some pause. 

I'm new to open source, but if you let me know what the problem is, I'd like to apply any small fixes and make a pull request if that would be helpful. 

## What versions are you using?
**Operating System:** macOS 11.4 Big Sur
**Package Version:** 5.4.9
**Browser Version:** Chrome 91.0.4472.114 (Official Build) (x86_64)

**Comment by anymaniax** [comment]
Thanks! fixed
