### ISSUE TITLE
Response type mismatch when using customFetch with output.httpClient set to "fetch"

### ISSUE THREAD

**Issue by AlmazHecker** [orval-labs/orval#1731]
here's my config
```typescript

import { defineConfig } from "orval";

export default defineConfig({
  shop: {
    input: {
      target: "http://localhost:8080/v3/api-docs",
    },
    output: {
      client: "react-query",
      target: "./api",
      mode: "tags-split",

      override: {
        mutator: {
          path: "./api/custom-fetch.ts",
          name: "baseFetch",
        },
      },
      prettier: true,
    },
  },
});

```

## What are the steps to reproduce this issue?

1. Use Orval with a custom fetch (custom-fetch.ts) as the mutator.
2. Set httpClient to fetch in the Orval config.
3. Generate API clients
4. Notice that the response is wrapped in an extra response object.

## What happens?
The response is being wrapped with another response object, which's structure is:

```
export type originalResponse {
  data: OriginalResponse;
  status: number;
  headers: Headers;
}
```

## What were you expecting to happen?
I expected to get original response without it's being wrapped into another response which causes type mismatch

## Any logs, error output, etc?
N/A

## What versions are you using?
Orval version 7.3.0

Please execute `npx envinfo --system --npmPackages orval,zod,axios,msw,swr,@tanstack/react-query,@tanstack/vue-query,react,vue` and paste the results here.

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 9 8945HS w/ Radeon 780M Graphics
    Memory: 1.93 GB / 15.29 GB

**Comment by AlmazHecker** [comment]
I guess there should be validation if config has both httpClient and mutator(custom fetch). Because now when I remove httpClient the generated api's are different

with httpClient and mutator(custom fetch) set:
```typescript
export type registerResponse = {
  data: RegisterResponse;
  status: number;
  headers: Headers;
};

export const getRegisterUrl = () => {
  return `/auth/register`;
};

export const register = async (
  registerRequest: RegisterRequest,
  options?: RequestInit,
): Promise<registerResponse> => {
  return baseFetch<Promise<registerResponse>>(getRegisterUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerRequest),
  });
};
```

mutator only:
```typescript
export const register = (
  registerRequest: RegisterRequest,
  options?: SecondParameter<typeof baseFetch>,
  signal?: AbortSignal,
) => {
  return baseFetch<RegisterResponse>(
    {
      url: `/auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: registerRequest,
      signal,
    },
    options,
  );
};
```

**Comment by soartec-lab** [comment]
@AlmazHecker 

Hmm, so when using `cutom-fetch`, do you want to return a `Promise` response instead of using the auto-generated response type?
Or is the problem that `RegisterResponse` does not exist in case of mutator only?

**Comment by soartec-lab** [comment]
They'll run into problems if users configure things in an inconsistent way.
I think the CLI could detect that and notice they, but i don't have any plans to address it.
If you create a PR, we'll be happy to accept it.
