### ISSUE TITLE
Mock generation fails when `items: string` used to define arrays in OpenAPI spec 

### ISSUE THREAD

**Issue by dcayers** [orval-labs/orval#1732]
## What are the steps to reproduce this issue?

1. Setup an OpenAPI spec using shorthand for simple arrays
```
openapi: 3.1.0
info:
  title: Simple API Example
  version: v1

paths:
  /items:
    get:
      summary: Get item details
      responses:
        "200":
          description: Item details with a list of tags
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 123
                  name:
                    type: string
                    example: Frozen Peas
                  categories:
                    type: array
                    items:
                      type: string # <-- This should be fine
                    example: ["frozen", "vegetables"]
                  tags:
                    type: array
                    items: string # <-- This is the culprit
                    example: ["new", "sale", "popular"]
                  price:
                    type: number
                    format: float
                    example: 3.99
```
2. Create simple orval config
```
import { defineConfig } from "orval";

type Config = ReturnType<typeof defineConfig>;

const config: Config = defineConfig({
  api: {
    input: {
      target: "./openapi.yaml",
    },
    output: {
      target: "./client.ts",
      mock: true, // Enable mocking
    },
  },
});

export default config;
```
3. Run `orval` script via package manager (in my case `pnpm generate`)

## What happens?

Code generation fails with errors referencing `Cannot use 'in' operator to search for '$ref' in string`

## What were you expecting to happen?

Mocks to be generated since `items: string` is valid OpenAPI syntax

## Any logs, error output, etc?

```
api - TypeError: Cannot use 'in' operator to search for '$ref' in string
    at getMockScalar (/../node_modules/.pnpm/@orval+mock@7.2.0_openapi-types@12.1.3/node_modules/@orval/mock/dist/index.js:343:18)
    at resolveMockValue (/../node_modules/.pnpm/@orval+mock@7.2.0_openapi-types@12.1.3/node_modules/@orval/mock/dist/index.js:565:18)
    at /../node_modules/.pnpm/@orval+mock@7.2.0_openapi-types@12.1.3/node_modules/@orval/mock/dist/index.js:174:29
    at Array.map (<anonymous>)
    at getMockObject (/../node_modules/.pnpm/@orval+mock@7.2.0_openapi-types@12.1.3/node_modules/@orval/mock/dist/index.js:164:8)
    at getMockScalar (/../node_modules/.pnpm/@orval+mock@7.2.0_openapi-types@12.1.3/node_modules/@orval/mock/dist/index.js:435:14)
    at resolveMockValue (/../node_modules/.pnpm/@orval+mock@7.2.0_openapi-types@12.1.3/node_modules/@orval/mock/dist/index.js:565:18)
    at /../node_modules/.pnpm/@orval+mock@7.2.0_openapi-types@12.1.3/node_modules/@orval/mock/dist/index.js:174:29
    at Array.map (<anonymous>)
    at getMockObject (/../node_modules/.pnpm/@orval+mock@7.2.0_openapi-types@12.1.3/node_modules/@orval/mock/dist/index.js:164:8)
```

## Any other comments?

Tracked the issue to this code from the error message: 

https://github.com/orval-labs/orval/blob/b23257b281f931a8a8a13cae43fb0f59cacf2763/packages/mock/src/faker/getters/scalar.ts#L180-L187

I reckon this just needs an update to account for this sort of shorthand array syntax. I don't have any context of the code to suggest a real fix, though. 

## What versions are you using?

 <ins>System:</ins>
      OS: macOS 14.5
      CPU: (11) arm64 Apple M3 Pro
      Memory: 73.50 MB / 18.00 GB
      Shell: 5.9 - /bin/zsh
      
<ins>npmPackages:</ins>
      axios: ^1.6.8 => 1.7.1 
      msw: ^2.2.14 => 2.2.14 
      orval: ^7.2.0 => 7.2.0 
      swr: ^2.2.5 => 2.2.5 
      zod: ^3.22.4 => 3.22.4

**Comment by AllieJonsson** [comment]
Is this supported? Swagger editor gives error on this using openapi 3.1.0
![image](https://github.com/user-attachments/assets/f5eff7fa-2f3d-45c0-ad66-768d12ecc45d)

**Comment by dcayers** [comment]
> Is this supported in openapi spec? Swagger editor gives error on this using openapi 3.1.0 ![image](https://private-user-images.githubusercontent.com/10475857/397888537-f5eff7fa-2f3d-45c0-ad66-768d12ecc45d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTMwNzYsIm5iZiI6MTczNDc1Mjc3NiwicGF0aCI6Ii8xMDQ3NTg1Ny8zOTc4ODg1MzctZjVlZmY3ZmEtMmYzZC00NWMwLWFkNjYtNzY4ZDEyZWNjNDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDAzNDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNGIzYzJmMzkwMGU0ZDdlOTBlMjI1ZjBiYTRhYWIwODU5ZDJiNmI3NjM4ZjJlZGZkNjI5OTgzNjJjOTdlYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1Yh600KWu-LttewDGl5I6dEktiYeD1JQ0e-Szj_fmZw)

I didn't think to try a different linter. The project I'm working on says this syntax is correct, but you're right, it doesn't track as valid when using the swagger editor. 

I updated the instances where we used `items: string` to match the valid example. Will close this one. 

Thanks for your response!
