### ISSUE TITLE
Orval is not generating all of the models found in OpenAPI json, but does try to import them in endpoints anyway

### ISSUE THREAD

**Issue by FranjoMindekPixion** [orval-labs/orval#1736]
## What are the steps to reproduce this issue?
1. Run orval with my specific orval configuration, orval version and OpenAPI json.

## What happens?
Orval doesn't generated all of the models found in OpenAPI json, but does try to import them as types in endpoints.
Previous versions of orval (6.31) generated those files successfully.
Not generated files are XEmbeddingOptions, XMetadataEmbeddingRecord and XMetadataSearchResult, where X is "Basic", "SentenceWindow", "AutoMerging", "HypotheticalQuestion" and "Hierarchical". 
Those types are generated from a generic type. They are defined in the OpenAPI file.

e.g. in generated file `sentence-window-strategy.ts`, we have:
```ts
import type {
  GetSentenceWindowEmbeddingOptionsParams,
  SentenceWindowEmbeddingOptions,
  SentenceWindowMetadataEmbeddingRecord,
  SentenceWindowMetadataSearchResult,
  SentenceWindowPreviewParams,
  SentenceWindowSearchParams,
} from "../../model";
import getSentenceWindowEmbeddingOptionsMutator from "../../axios";
import sentenceWindowSearchMutator from "../../axios";
import sentenceWindowPreviewMutator from "../../axios";
```
Types `SentenceWindowEmbeddingOptions`, `SentenceWindowMetadataEmbeddingRecord`, and `SentenceWindowMetadataSearchResult` don't exist.

## What were you expecting to happen?
Models which are imported in endpoints are generated successfully.

## Any logs, error output, etc?
🍻 Start orval v7.3.0 - A swagger client generator for typescript
(node:34056) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
learn-rag-client: Cleaning output folder
🎉 learn-rag-client - Your OpenAPI spec has been converted into ready to use orval!

## Any other comments?
OpenAPI json: https://pastebin.com/SsReLbQp

orval.config.ts
```ts
import { defineConfig } from "orval";

export default defineConfig({
  "learn-rag-client": {
    input: {
      target: "http://localhost:5186/swagger/v1/swagger.json",
      filters: {},
    },
    output: {
      client: "axios-functions",
      workspace: "src/api/",
      target: "./endpoints",
      schemas: "./model",
      mode: "tags-split",
      clean: true,
      prettier: true,
      urlEncodeParameters: true,
      allParamsOptional: false,
      override: {
        useTypeOverInterfaces: true,
        mutator: {
          path: "./axios.ts",
        },
      },
    },
  },
});
```

axios.ts
```ts
import Axios, { type AxiosRequestConfig } from "axios";

const axios = Axios.create();

export default async function customInstance<T>(
  config: AxiosRequestConfig,
  options?: AxiosRequestConfig
): Promise<T> {
  const { data } = await axios<T>({ ...config, ...options });
  return data;
}
```

workspace folder:
```
│   axios.ts
│   index.ts
│
├───endpoints
│   ├───auto-merging-strategy
│   │       auto-merging-strategy.ts
│   │
│   ├───basic-strategy
│   │       basic-strategy.ts
│   │
│   ├───documents
│   │       documents.ts
│   │
│   ├───hierarchical-strategy
│   │       hierarchical-strategy.ts
│   │
│   ├───hypothetical-question-strategy
│   │       hypothetical-question-strategy.ts
│   │
│   ├───rag-endpoints
│   │       rag-endpoints.ts
│   │
│   └───sentence-window-strategy
│           sentence-window-strategy.ts
│
└───model
        autoMergingPreviewParams.ts
        autoMergingSearchParams.ts
        basicPreviewParams.ts
        basicSearchParams.ts
        getAutoMergingEmbeddingOptionsParams.ts
        getBasicEmbeddingOptionsParams.ts
        getHierarchicalEmbeddingOptionsParams.ts
        getHypotheticalQuestionEmbeddingOptionsParams.ts
        getSentenceWindowEmbeddingOptionsParams.ts
        hierarchicalPreviewParams.ts
        hierarchicalSearchParams.ts
        hypotheticalQuestionPreviewParams.ts
        hypotheticalQuestionSearchParams.ts
        index.ts
        sentenceWindowPreviewParams.ts
        sentenceWindowSearchParams.ts
```

## What versions are you using?
System:
  OS: Windows 11 10.0.22631
  CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1250U
  Memory: 2.14 GB / 15.63 GB
npmPackages:
  axios: ^1.7.7 => 1.7.7
  orval: ^7.3 => 7.3.0
  react: ^18.3.1 => 18.3.1

**Comment by sebastijandumancic** [comment]
Try removing `filters` in the orval.config.ts. Had the same issue, seem like the whole filters part is unsupported in 7.3.x

**Comment by borisyordanov** [comment]
We're experiencing the same issue but @sebastijandumancic 's workaround is valid.

**Comment by FranjoMindekPixion** [comment]
Can confirm, removing `filters` fixed the issue.

**Comment by melloware** [comment]
I wonder if `filters: {}` should be ignored as if Filters was not set at all?

**Comment by melloware** [comment]
I submitted a PR: https://github.com/orval-labs/orval/pull/1740
