### ISSUE TITLE
Add `sortFields = true|false` to disable sorting when generating the model

### ISSUE THREAD

**Issue by nimo23** [orval-labs/orval#1737]
Orval generates `*.ts` model files from a given `openapi.yml`. However, the fields within the `*.ts` model interface/type are always sorted implicitly instead of using the field order defined in `openapi.yml`. For example:

## What are the steps to reproduce this issue?

1.`openapi.yml` has a `User` endpoint with the following

```
openapi: 3.1.0
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        password:
          type: string
```

2. let orval generate the `user.ts` and look at the ordering of the fields:

```
// overal sorts the fields in alphabetical order
export interface User {
  id?: string;
  password?: string;
  username?: string;
}
```

Please add a configuration to https://orval.dev/reference/configuration/output, e.g. `sortFields = true|false`. If set to `false`, the field order should match the order defined in `openapi.yml`. In the above example, it should be:

```
// sortFields=false, i.e. overal uses the sorting order as defined in openapi.yml
export interface User {
  id?: string;
  username?: string;
  password?: string;
}
```

## What versions are you using?
Orval v 7.3.0

**Comment by melloware** [comment]
Similar to this issue too: https://github.com/orval-labs/orval/issues/1382  I think in general everything should be sorted alpha if possible and this new flag suggested by @nimo23 would basically ignore all sorting...

**Comment by melloware** [comment]
PR is welcome...
