### ISSUE TITLE
Wrong check in query params to add in the url

### ISSUE THREAD

**Issue by vinibgoulart** [orval-labs/orval#1760]
## What are the steps to reproduce this issue?

1. Create an route with query param
2. Generate the functions
3. Use some function sending the query params
4. Check the request does not contain the query parameters

## What happens?

When mount the query params to some URL, the flow are checking by `normalizedParams.size` to add in the URL these params, but it's null even there is query params sent

## What were you expecting to happen?

Check correctly the query params to add in the URL

## Any logs, error output, etc?

<img width="854" alt="image" src="https://github.com/user-attachments/assets/5a0b2a40-0350-4ab8-8248-d52189db8983" />

## Any other comments?

There is some workaround for this?

## What versions are you using?

```
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 85.19 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
```

```json
    "orval": "^7.3.0",
    "zod": "^3.23.8"
    "@tanstack/react-query": "^5.62.7",
```

```ts
input: {
      target: `${process.env.API_URL}/doc`,
    },
    output: {
      mode: 'tags-split',
      target: './src/schema/schema.ts',
      schemas: './src/schema/model',
      client: 'react-query',
      httpClient: 'fetch',
      baseUrl: process.env.API_URL,
    },
```

**Comment by AllieJonsson** [comment]
What does your `GetAlertParams` type look like?
What data do you send to the function?

**Comment by vinibgoulart** [comment]
If I test this on some node process, the `size` property works fine, but in this generated code, the `size` remains undefined

**Comment by vinibgoulart** [comment]
> What does your `GetAlertParams` type look like? What data do you send to the function?

<img width="704" alt="image" src="https://github.com/user-attachments/assets/f619597a-e8ee-4514-bd5e-2ac192744ac3" />
<img width="370" alt="image" src="https://github.com/user-attachments/assets/bf264b24-4fce-4e5e-adba-0a8a07f5531f" />

**Comment by AllieJonsson** [comment]
What browser are you running this in? Maybe there is some browser shenanigans happening here...

**Comment by vinibgoulart** [comment]
> What browser are you running this in? Maybe there is some browser shenanigans happening here...

Expo project

```json
"expo": "~51.0.28",
```

**Comment by vinibgoulart** [comment]
I can solve this issue following this comment: https://github.com/facebook/react-native/issues/38656#issuecomment-1660117381

**Comment by joernroeder** [comment]
same issue here. this might be an interesting use case for @evanbacon bc this is one of the bugs which is easy to miss building universal apps and I believe expo-router does some things based on URLs too. would be nice if expo would take care of the differences here.
