### ISSUE TITLE
Type Inference Issue: fetch Response Data Typed as unknown When Using @cloudflare/workers-types with Orval Fetch Client

### ISSUE THREAD

**Issue by him0** [orval-labs/orval#1761]
## What are the steps to reproduce this issue?

1. Install the npm package @cloudflare/workers-types in your project.
2. Configure orval.config.ts with the following:

```ts
import { defineConfig } from "orval";

export default defineConfig({
  auth: {
    input: "./openapi.json",
    output: {
      mode: "single",
      target: "./output.ts",
      indexFiles: false,
      client: "fetch",
    },
  },
});
```

3.Run the orval command to generate the client.

## What happens?

When the client is generated, the line `const data = await res.json();` results in data being typed as unknown, causing type errors in TypeScript when trying to use the response data.

![CleanShot 2024-12-21 at 23 05 25](https://github.com/user-attachments/assets/e15ff206-0ca3-4db2-869c-30737fb2b2b3)

In @cloudflare/workers-types, the type definition of fetch is overridden, and when fetch does not take type parameters, data is treated as unknown, which causes this issue.

I have prepared a repository that reproduces the issue. You can find it here: [Reproduction Repository](https://github.com/him0/orval-fetch-error).

## What were you expecting to happen?

The expected result is that data should have a defined type, like `const data: RootGetIndexResponse = await res.json();`, which would resolve this issue.

## What versions are you using?

- Node.js: 22.11.0
- DevDependencies:
  - `@cloudflare/workers-types`: ^4.20241205.0
  - `orval`: ^7.3.0
  - `typescript`: ^5.7.2

**Comment by soartec-lab** [comment]
Thanks you for made this report.
Certainly, it would be preferable to use a type declaration instead of `as` 👍 

```diff
- const data = await res.json();
- data as Pet;

+ const data: Pets = await res.json();
+ return data;
```
