### ISSUE TITLE
allOf of two schemas generates a never type instead of a correct combination

### ISSUE THREAD

**Issue by mvpr-adrian** [orval-labs/orval#1766]
## What are the steps to reproduce this issue?

1. Create openapi spec with two components A, B
2. B is created by referencing A in an "allOf" and overrides A's property
3. The resulted typescript type for B is "never"

## What happens?

```json
"components": {
  "A": {
    "type": "object",
    "properties": {
      "name": { "type": "string" },
      "status": {
        "type": "string",
        "enum": ["a", "b"]
        }
    }
  },
  "B": {
    "allOf": [
      { "$ref": "#/components/A" },
      {
        "type": "object",
        "properties": {
          "status": {
            "type": "string", 
            "enum": ["c", "d"]
          }
        }
      }
    ]
  }
}
```

```ts
export type BAllOfStatus = (typeof BAllOfStatus)[keyof typeof BAllOfStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BAllOfStatus = {
  c: 'c',
  b: 'b',
} as const;

export type BAllOf = {
  status?: BAllOfStatus;
};

// type B is "never"
export type B = A & BAllOf;
```

## What were you expecting to happen?

```ts
export type BAllOfStatus = (typeof BAllOfStatus)[keyof typeof BAllOfStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BAllOfStatus = {
  c: 'c',
  b: 'b',
} as const;

export type BAllOf = {
  status?: BAllOfStatus;
};

// type B is is "A & B"
export type B = Omit<A, 'status'> & BAllOf;
```

## Any logs, error output, etc?

…

## Any other comments?

…

## What versions are you using?

Please execute
```
  System:
    OS: macOS 15.2
    CPU: (8) arm64 Apple M2
    Memory: 212.16 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    orval: ^7.3.0 => 7.3.0 
    react: ^18.2.0 => 18.2.0 
```

**Comment by AllieJonsson** [comment]
This should probably be fixed, but in the meantime you could change your schema to
```json
      "Base": {
        "type": "object",
        "properties": {
          "name": { "type": "string" }
        }
      },
      "A": {
        "allOf": [
          { "$ref": "#/components/schemas/Base" },
          {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": ["a", "b"]
            }
        }}]
      },
      "B": {
        "allOf": [
          { "$ref": "#/components/schemas/Base" },
          {
            "type": "object",
            "properties": {
              "status": {
                "type": "string", 
                "enum": ["c", "d"]
              }
            }
          }
        ]
      }
```

**Comment by mvpr-adrian** [comment]
> This should probably be fixed, but in the meantime you could change your schema to
> 
> ```json
>       "Base": {
>         "type": "object",
>         "properties": {
>           "name": { "type": "string" }
>         }
>       },
>       "A": {
>         "allOf": [
>           { "$ref": "#/components/schemas/Base" },
>           {
>         "type": "object",
>         "properties": {
>           "status": {
>             "type": "string",
>             "enum": ["a", "b"]
>             }
>         }}]
>       },
>       "B": {
>         "allOf": [
>           { "$ref": "#/components/schemas/Base" },
>           {
>             "type": "object",
>             "properties": {
>               "status": {
>                 "type": "string", 
>                 "enum": ["c", "d"]
>               }
>             }
>           }
>         ]
>       }
> ```

nice thanks, I'll implement the workaround for now 🙌

**Comment by AllieJonsson** [comment]
I thought about this for a while, I'm not sure we can implement your suggestion. I'm afraid if there could be instances where we don't know which property that should be the "prioritized" property... I think best would be to do something like the workaround to avoid any ambiguities.

**Comment by melloware** [comment]
I agree with @AllieJonsson its tough to know all these situations and ordering.
