### ISSUE TITLE
`react-query` + custom `axios` instance mutator & passing additional `AxiosConfig` like `headers`

### ISSUE THREAD

**Issue by mayteio** [orval-labs/orval#224]
Firstly - thank you for creating this tool. It has saved probably hundreds of hours creating our own client and is so configurable!

We'd basically like to be able to pass `config:AxiosConfig` rather than `body` in an operation with a custom mutator. Any help much appreciated :) 

Possibly related/conflicting issue: https://github.com/anymaniax/orval/issues/124#issuecomment-839781349

## What are the steps to reproduce this issue?
Without a custom mutator, the generated operation allows for a second argument:
```ts
export const getPetById = (
  bodyGetPetById: BodyGetPetById,
  options?: AxiosRequestConfig // <-- awesome!
): Promise<AxiosResponse<Token>> => {
  return axios.post(
    `/api/auth/token`,
    bodyGetPetById,
    options // <-- awesome!
  );
};
```

If we use a custom axios instance however similar to the docs:
```ts
// we create multiple clients, thus the need for `createClient`
export const AXIOS_INSTANCE = Axios.create({ baseURL: "" });
export function createClient(instance: AxiosInstance) {
  return <T>(config: AxiosRequestConfig): Promise<T> => {
    const source = Axios.CancelToken.source();
    const promise = instance({
      ...config,
      cancelToken: source.token,
    }).then(({ data }) => data);

    // @ts-expect-error
    promise.cancel = source.cancel;

    return promise;
  };
}

export const apiClient = createClient(AXIOS_INSTSTANCE);
```
And used in config:
```
{
   petStore: {
     output: {
        override: {
          mutator: {
            path: "src/api-client.ts",
            name: "apiClient",
          },
        }
      }
   }
}
```
Then the second argument is lost, and we can't pass any additional config to the axios call, like headers:
```ts
export const getPetById = (
  bodyUpdatePetById: BodyUpdatePetById
  // options is missing, or ^bodyUpdatePetById^ could be config
) => {
  return apiClient<Token>({
    url: `/api/auth/token`,
    method: "post",
    data: bodyGetPetById,
    // ...options or ...config is missing
  });
};
```

Our current workaround is to use an interceptor before making the call, then ejecting the interceptor afterwards like;
```ts
const {slug} = useParams() // get slug from URL
const eject = addSlugHeader(slug) // use interceptor on instance
await updatePet(...) // call generated function
eject() // eject interceptor on instance
```
But this is prone to human error to remember and we only need it for a handful of calls, so don't want to use global config.

## What happens?
The second argument is not generated when a custom mutator is passed

## What were you expecting to happen?
The second argument should forward to my custom mutator, or we should have an option on how to deal with second options

I'm guessing I might need to use a [custom client](https://orval.dev/reference/configuration/output#client), but the links in the docs go to the wrong lines in the source. An example on creating a custom client would be a huge help! 🙌

## What versions are you using?
**Operating System:** macOS
**Package Version:** 6.2.0
**Browser Version:** Chrome 93

**Comment by anymaniax** [comment]
Hello @mayteio, normally if you add the second argument in your mutator fonction and regenerate. You should see the options. Orval read your mutator file to see if your mutator have a second argument.
