### ISSUE TITLE
Prettier doesn't run without schemas

### ISSUE THREAD

**Issue by ptrckhjnl** [orval-labs/orval#234]
## What are the steps to reproduce this issue?
1. Create a config that does not have `{ output: { schemas: ... } }` (but it has `target: ...` and `prettier: true`)
2. Run `orval`

## What happens?
The generated code is not formatted.

## What were you expecting to happen?
The code to be formatted.

## Any other comments?
It's probably because of this line: https://github.com/anymaniax/orval/blob/master/src/core/writers/specs.ts#L140

Here it should probably also check if the config contains a `target`.

But according to the docs (https://orval.dev/reference/configuration/output#schemas) if no `schemas` is given, `target` is used as the default value.

**Comment by anymaniax** [comment]
Everything seems to work correctly on my side. Do you have prettier in your dev dependencies?

**Comment by melloware** [comment]
This is easy enough to do. 

```JS

"scripts": {
		"format": "prettier --write \"{src,__tests__}/**/*.{ts,tsx}\"",
		"codegen": "orval && npm run format",
		"start": "react-app-rewired start"

```
