### ISSUE TITLE
MSW: Add "x-faker" support for yaml openapi yaml files

### ISSUE THREAD

**Issue by PeterMK85** [orval-labs/orval#279]
Question/Feature :)
_(checked issues, no references so far)_

[Example](https://github.com/Fredx87/openapi-mock-generator#fakerjs-and-chance-methods)

## What are the steps to reproduce this issue?
1. Create a yaml declaration:
```yaml
    "first_name": {
      "type": "string",
      "x-faker": "name.firstName"
    },
```
2. If `mock` true in the orval.config.js
3. The generated msw mocks should respect the x-faker value and directly set for the fields

## What happens?
At the moment being ignored

## What were you expecting to happen?
The generated msw mocks should respect the x-faker value from the yaml file declaration

## Any logs, error output, etc?
-

## Any other comments?
-

There is a possible mutator where the `yaml` file can be accessed?

## What versions are you using?
**Operating System:** …
**Package Version:** …
**Browser Version:** …

**Comment by melloware** [comment]
cc @Will-Mann-16

**Comment by soartec-lab** [comment]
Using `orverride.mock.useExamples` will solve this problem 👍 

https://orval.dev/reference/configuration/output#useexamples-1

**Comment by douglasg14b** [comment]
@soartec-lab that doesn't really solve the problem from a code generation perspective. 

`x-faker` enables APIs to specify the _flavor_ of the properties on their models, and leaves the faking implementation details to a tool suited for the job, faker. Examples require the API to specify specific examples for each property, which moves the burden of producing specific examples to the API itself. 

This quickly becomes unsustainable in cases where you want many different codegenned ranged for various properties. These unsustainable used cases are achieved easily in trivial APIs.
