### ISSUE TITLE
Proposal: Add ability to skip the index file generation

### ISSUE THREAD

**Issue by yekver** [orval-labs/orval#336]
I faced with a situation when exported interfaced from different schema files can have the same names. This causes errors `TS2300 (Duplicate identifier 'MyDuplicatedTypeName')` in `index.ts` file.
We can add an ability to skip generation of the `index.ts` file to deal with such cases or convert `exports` to `named exports` to provide namespacing

**Comment by yekver** [comment]
Looks like this issue can be linked to #335

**Comment by soartec-lab** [comment]
iI believe this issue was probably resolved in #1104, so I'll close it.
