### ISSUE TITLE
Add additional support for more JSON Schema keywords (minLength, maxLength, etc.)

### ISSUE THREAD

**Issue by achendrick** [orval-labs/orval#338]
## What are the steps to reproduce this issue?
1. I ran orval against an OpenApi 3.0 spec with some of the following rules and saw no reference to them:
```jsonc
AnObjectDto: {
  type: "object",
  properties: {
    key: {
      maxLength: 30,
      minLength: 0,
      pattern: "\A(\w|-)+\Z",
      type: "string"
    },
    name: {
      maxLength: 100,
      minLength: 0,
      pattern: "\A(?!\s*\Z).+\Z",
      type: "string"
    },
    // ...
}
```

## What happens?
I see no references to `maxLength`, `minLength` or `pattern` and I'd suspect other [keywords](https://swagger.io/docs/specification/data-models/keywords/) are missing as well.
I _do_ see references to enums, which is great!

## What were you expecting to happen?
I'd expect either an object with references to these rules to be created or even individual constants created similar to how `enum` is treated.

Ideally:
```typescript
export const AnObjectDtoKey = {
  maxLength: 30,
  minLength: 0,
  pattern: "\A(\w|-)+\Z"
};
```
Or:
```typescript
export const AnObjectDtoKeyMaxLength = 30;
export const AnObjectDtoKeyMinLength = 0;
export const AnObjectDtoKeyPattern = "\A(\w|-)+\Z";
```

## Any logs, error output, etc?
None seen

## Any other comments?
Love the library and I'm really hoping I can leverage it to help with data validation.
I primarily use [Yup](https://github.com/jquense/yup) for client validation and I could take one of these generated values and use it along with it.

## What versions are you using?
**Operating System:** macOS 12.2.1 (Monterey)
**Package Version:** `6.5.3`
**Browser Version:** Brave [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (x86_64)](https://brave.com/latest/)

**Comment by soartec-lab** [comment]
Currently we support `zod` and you can use these in your schema validation.
