### ISSUE TITLE
Missing question mark that separate URL from query string parameters

### ISSUE THREAD

**Issue by Neosyn-Alex-Ferreli** [orval-labs/orval#482]
## What are the steps to reproduce this issue?

Generate react-hooks based on a Swagger-file with a GET request that need parameters in query string like this:
/api/users?name=alex&surname=ferreli

## What happens?

React-hooks begin generated without **question mark**:
/api/usersname=alex&surname=ferreli

Backend didn't understand the request and respond 404.

## What were you expecting to happen?

I expect that the API is called with **question mark** that separate URL from parameters.

## Any logs, error output, etc?

Just a 404 on DevTools because of wrong generated URL

## What versions are you using?

**Operating System:** Windows 10
**Package Version:** latest, v6.8.1
**Browser Version:** Chrome 103

**Comment by melloware** [comment]
Closing this as no response from OP and I have not had any issues with query params in any of my apps
