### ISSUE TITLE
MSW: @mswjs/data support

### ISSUE THREAD

**Issue by dave-500** [orval-labs/orval#700]
Hi is there any plan to support the @mswjs/data library? [https://github.com/mswjs/data](https://github.com/mswjs/data)

**Comment by anymaniax** [comment]
Hello @dave-500, I did some tests at the release and didn't find any good way to support it. So, it's currently not planned. If you want to work on it and come up with something I will be happy to help you.

**Comment by melloware** [comment]
@Will-Mann-16 can you look at this and if it is not possible let's close this ticket.

**Comment by soartec-lab** [comment]
@melloware 
I checked this out too but I don't have any plans so can I just close this?
